config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :mothers
  resources :litters
  resources :puppies

  get 'our_dogs', to: 'pages#our_dogs'
  get 'contact', to: 'pages#contact'

  root to: 'pages#home'
end

app/models/litter.rb
class Litter < ApplicationRecord
  belongs_to :mother
  has_many :puppies
 extend FriendlyId
  friendly_id :date, use: :slugged

  mount_uploader :main_image, ImageUploader
  mount_uploader :image_one, ImageUploader
  mount_uploader :image_two, ImageUploader
end

app/controllers/litters_controller.rb
class LittersController < ApplicationController
  before_action :set_litter, only: [:show, :edit, :update, :destroy]
  access all: [:show], admin: :all

  # GET /litters
  # GET /litters.json
  def index
    @litters = Litter.all
  end

  # GET /litters/1
  # GET /litters/1.json
  def show
  end

  # GET /litters/new
  def new   
    @mother = Mother.find_by_name(params[:mother_name])  
    @litter = Litter.new
    
    if @mother != nil
      @litter.mother_id = @mother.id      
    else
    redirect_to root_path, notice: 'To add a new litter please navigate to Our dogs, the mother you wish to add a new litter for and use the new litter feature.'
    end
  end

  # GET /litters/1/edit
  def edit
  end

  # POST /litters
  # POST /litters.json
  def create        
    @litter = Litter.new(litter_params)
    respond_to do |format|
      if @litter.save
        format.html { redirect_to @litter, notice: 'Litter was successfully created.' }
        format.json { render :show, status: :created, location: @litter }
      else
        format.html { render :new }
        format.json { render json: @litter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /litters/1
  # PATCH/PUT /litters/1.json
  def update
    respond_to do |format|
      if @litter.update(litter_params)
        format.html { redirect_to @litter, notice: 'Litter was successfully updated.' }
        format.json { render :show, status: :ok, location: @litter }
      else
        format.html { render :edit }
        format.json { render json: @litter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /litters/1
  # DELETE /litters/1.json
  def destroy
    @litter.destroy
    respond_to do |format|
      format.html { redirect_to litters_url, notice: 'Litter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_litter
      @litter = Litter.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def litter_params
      params.require(:litter).permit(:date, :about, :main_image, :image_one, :image_two, :mother_id)
    end
end

app/helpers/litters_helper.rb
module LittersHelper
end

app/views/litters/_form.html.erb
<%= params[:mother_name] %>
<hr>
<%= @mother.inspect %>
<hr>
<%= form_with(model: litter, local: true) do |form| %>
  <% if litter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(litter.errors.count, "error") %> prohibited this litter from being saved:</h2>

      <ul>
      <% litter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  

  <%= form.hidden_field :mother_id, value: litter.mother_id %>  

  <div class="field form-control col-md-2">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div> 
  
  <div class="col-md-6">
    <%= form.label :about %>
    <%= form.text_area :about, rows: 8, class: 'form-control' %>
  </div>
  <br>
  <div class="form-control-file">
    <%= form.file_field :main_image %>
  </div>
  <br>    
  <%= form.submit %>
  </div>
<% end %>

app/views/litters/edit.html.erb
<h1>Editing Litter</h1>

<%= render 'form', litter: @litter %>

<%= link_to 'Show', @litter %> |
<%= link_to 'Back', litters_path %>

app/views/litters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Litters</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>About</th>
      <th>Main image</th>
      <th>Image one</th>
      <th>Image two</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @litters.each do |litter| %>
      <tr>
        <td><%= litter.date %></td>
        <td><%= litter.about %></td>
        <td><%= litter.main_image %></td>
        <td><%= litter.image_one %></td>
        <td><%= litter.image_two %></td>
        <td><%= link_to 'Show', litter %></td>
        <td><%= link_to 'Edit', edit_litter_path(litter) %></td>
        <td><%= link_to 'Destroy', litter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Litter', new_litter_path %>

app/views/litters/new.html.erb
<h1>New Litter</h1>

<%= render 'form', litter: @litter %>

<%= link_to 'Back', litters_path %>

app/views/litters/show.html.erb
<div class="visitor-background">
  <p id="notice"><%= notice %></p>
  <hr>
  <%= @mother.inspect %>
  <hr>
  <%= link_to 'Edit Litter', edit_litter_path(@litter) if logged_in?(:admin) %>
  <br>
  <%= link_to 'New Puppy', new_puppy_path(mother_id: @litter.mother_id, litter_date: @litter.date) if logged_in?(:admin) %>
  <br>
  <%= image_tag @litter.main_image.url, class:'image' unless @litter.main_image.url.nil? %>
  <hr>
  <% @litter.puppies.each do |puppy| %>
    <div class="row">
      <div class="col-md-4 image">
        <%= link_to (image_tag puppy.main_image.url, class:'image'), puppy_path(puppy.slug) unless puppy.main_image.url.nil? %>
      </div>
      <div class="col-md-8 about">
        <p><%= puppy.about %></p>
      </div>
    </div>
  <% end %>
</div>