config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :mothers
  resources :litters
  resources :puppies

  get 'our_dogs', to: 'pages#our_dogs'
  get 'contact', to: 'pages#contact'

  root to: 'pages#home'
end

app/models/mother.rb
class Mother < ApplicationRecord
  has_many :litters    

  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :main_image, ImageUploader
  mount_uploader :image_one, ImageUploader
  mount_uploader :image_two, ImageUploader
end

app/controllers/mothers_controller.rb
class MothersController < ApplicationController
  before_action :set_mother, only: [:show, :edit, :update, :destroy]
  access all: [:show], admin: :all

  # GET /mothers
  # GET /mothers.json
  def index
    @mothers = Mother.all
  end

  # GET /mothers/1
  # GET /mothers/1.json
  def show
  end

  # GET /mothers/new
  def new
    @mother = Mother.new
  end

  # GET /mothers/1/edit
  def edit
  end

  # POST /mothers
  # POST /mothers.json
  def create
    @mother = Mother.new(mother_params)

    respond_to do |format|
      if @mother.save
        format.html { redirect_to @mother, notice: 'Mother was successfully created.' }
        format.json { render :show, status: :created, location: @mother }
      else
        format.html { render :new }
        format.json { render json: @mother.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mothers/1
  # PATCH/PUT /mothers/1.json
  def update
    respond_to do |format|
      if @mother.update(mother_params)
        format.html { redirect_to @mother, notice: 'Mother was successfully updated.' }
        format.json { render :show, status: :ok, location: @mother }
      else
        format.html { render :edit }
        format.json { render json: @mother.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mothers/1
  # DELETE /mothers/1.json
  def destroy
    @mother.destroy
    respond_to do |format|
      format.html { redirect_to mothers_url, notice: 'Mother was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mother
      @mother = Mother.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mother_params
      params.require(:mother).permit(:name, :about, :main_image, :image_one, :image_two)
    end
end

app/helpers/mothers_helper.rb
module MothersHelper
end

app/views/mothers/_form.html.erb
<%= form_with(model: mother, local: true) do |form| %>
  <% if mother.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mother.errors.count, "error") %> prohibited this mother from being saved:</h2>

      <ul>
      <% mother.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"> 
    <div class="col-md-2">
      <%= form.label :name %>
      <%= form.text_field :name, class:"form-control" %>
    </div>
    <div class="col-md-6">
      <%= form.label :about %>
      <%= form.text_area :about, rows: 8, class: 'form-control'  %>
    </div>
    <br>
    <div class="form-control-file">
      <%= form.file_field :main_image %>
    </div>
    <br>    
    <%= form.submit %>
  </div>
<% end %>

app/views/mothers/edit.html.erb
<h1>Editing Mother</h1>

<%= render 'form', mother: @mother %>

<%= link_to 'Show', @mother %> |
<%= link_to 'Back', mothers_path %>

app/views/mothers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mothers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mothers.each do |mother| %>
      <tr>
        <td><%= mother.name %></td>
        <td><%= mother.about %></td>
        <td><%= link_to 'Show', mother %></td>
        <td><%= link_to 'Edit', edit_mother_path(mother) %></td>
        <td><%= link_to 'Destroy', mother, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mother', new_mother_path %>

app/views/mothers/new.html.erb
<h1>New Mother</h1>

<%= render 'form', mother: @mother %>

<%= link_to 'Back', mothers_path %>

app/views/mothers/show.html.erb
<div class="visitor-background">
  <p id="notice"><%= notice %></p>
  <%= link_to 'Edit Mother', edit_mother_path(@mother) if logged_in?(:admin) %>
  <br>
  <%= link_to 'New Litter', new_litter_path(mother_name: @mother.name) if logged_in?(:admin) %>

  <div class="row">
    <div class="col-md-4 image">
      <%= image_tag @mother.main_image.url, class:'image' unless @mother.main_image.url.nil? %>
    </div>
    <div class="col-md-8 about">
      <p><%= @mother.about %></p>
    </div>
  </div>

  <% @mother.litters.each do |litter| %>
    <div class="row">
      <div class="col-md-4 image">
        <%= link_to (image_tag litter.main_image.url, class:'image'), litter_path(litter.slug) unless @mother.main_image.url.nil? %>
      </div>
      <div class="col-md-8 about">
        <p><%= litter.about %></p>
      </div>
    </div>
  <% end %>
</div>