config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :mothers
  resources :litters
  resources :puppies

  get 'our_dogs', to: 'pages#our_dogs'
  get 'contact', to: 'pages#contact'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<h1>Footer</h1>

app/views/shared/_application_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="navbar-brand" <%= link_to "Site Logo", root_path %></a>
      </li>
      <li class="nav-item">
        <a class="navbar-brand" <%= link_to 'Our dogs', our_dogs_path %></a>
      </li>
      <li class="nav-item">
        <a class="navbar-brand" <%= link_to 'Contact us', contact_path %></a>
      </li>      
    </ul>
  </div>
</nav>

app/views/shared/_puppy.html.erb
<div class="row">
  <div class="col-md-1 image">
  </div>
  <div class="col-md-4 image puppy">
    <%= link_to (image_tag puppy.main_image.url, class:'image'), puppy_path(puppy.id) unless puppy.main_image.url.nil? %>
  </div>
  <div class="col-md-5 about card-body" >
    <p><%= puppy.about %></p>
  </div>
  <div class="col-md-2 image">
  </div>
</div>