config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :mothers
  resources :litters
  resources :puppies

  get 'our_dogs', to: 'pages#our_dogs'
  get 'contact', to: 'pages#contact'

  root to: 'pages#home'
end

app/models/puppy.rb
class Puppy < ApplicationRecord
  belongs_to :litters, optional: :true
  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :main_image, ImageUploader
  mount_uploader :image_one, ImageUploader
  mount_uploader :image_two, ImageUploader
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  before_action :set_puppy, only: [:show, :edit, :update, :destroy]   
  access all: [:show], admin: :all

  # GET /puppies
  # GET /puppies.json
  def index
    @puppies = Puppy.all
  end

  # GET /puppies/1
  # GET /puppies/1.json
  def show
    @puppies = Puppy.all
  end

  # GET /puppies/new
  def new    
    @mother = Mother.find(params[:mother_id])  
    @litter = Litter.find_by_date(params[:litter_date]) && Litter.find_by_mother_id(params[:mother_id])  
    @puppy = Puppy.new

    if @litter != nil
      @puppy.litter_id = @litter.id      
    else
    redirect_to root_path, notice: 'To add a new litter please navigate to Our dogs, the mother you wish to add a new puppy for, select the litter and use the new puppy feature.'
    end
  end

  # GET /puppies/1/edit
  def edit
  end

  # POST /puppies
  # POST /puppies.json
  def create
    @puppy = Puppy.new(puppy_params)
    respond_to do |format|
      if @puppy.save
        format.html { redirect_to @puppy, notice: 'Puppy was successfully created.' }
        format.json { render :show, status: :created, location: @puppy }
      else
        format.html { render :new }
        format.json { render json: @puppy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puppies/1
  # PATCH/PUT /puppies/1.json
  def update
    respond_to do |format|
      if @puppy.update(puppy_params)
        format.html { redirect_to @puppy, notice: 'Puppy was successfully updated.' }
        format.json { render :show, status: :ok, location: @puppy }
      else
        format.html { render :edit }
        format.json { render json: @puppy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puppies/1
  # DELETE /puppies/1.json
  def destroy
    @puppy.destroy
    respond_to do |format|
      format.html { redirect_to puppies_url, notice: 'Puppy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puppy
      @puppy = Puppy.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puppy_params
      params.require(:puppy).permit( :name, :about, :main_image, :image_one, :image_two, :price, :litter_id)
    end
end

app/helpers/puppies_helper.rb
module PuppiesHelper
end

app/views/puppies/_form.html.erb
<%= form_with(model: puppy, local: true) do |form| %>
  <% if puppy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(puppy.errors.count, "error") %> prohibited this puppy from being saved:</h2>

      <ul>
      <% puppy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :litter_id, value: puppy.litter_id %> 

  <div class="field"> 
    <div class="col-md-2">
      <%= form.label :name %>
      <%= form.text_field :name, class:"form-control" %>
    </div>
    <div class="col-md-2">
      <%= form.label :price %>
      <%= form.text_field :price, class:"form-control" %>
    </div>
    <div class="col-md-6">
      <%= form.label :about %>
      <%= form.text_area :about, rows: 8, class: 'form-control'  %>
    </div>
    <br>
    <div class="form-control-file">
      <%= form.file_field :main_image %>
    </div>
    <br>    
    <%= form.submit %>
  </div>
<% end %>

app/views/puppies/edit.html.erb
<h1>Editing Puppy</h1>

<%= render 'form', puppy: @puppy %>

<%= link_to 'Show', @puppy %> |
<%= link_to 'Back', puppies_path %>

app/views/puppies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Puppies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puppies.each do |puppy| %>
      <tr>
        <td><%= link_to 'Show', puppy %></td>
        <td><%= link_to 'Edit', edit_puppy_path(puppy) %></td>
        <td><%= link_to 'Destroy', puppy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Puppy', new_puppy_path %>

app/views/puppies/new.html.erb
<h1>New Puppy</h1>

<%= render 'form', puppy: @puppy %>

<%= link_to 'Back', puppies_path %>

app/views/puppies/show.html.erb
<div class="visitor-background">
  <p id="notice"><%= notice %></p>

  <%= link_to 'Edit Puppy', edit_puppy_path(@puppy) if logged_in?(:admin) %>
  <%= render 'shared/puppy', puppy: @puppy %>
</div>